---
title: "Bootstrap"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
faces <- read_csv('../Data/cleaned_FACES_data.csv', col_types = c('ffffdf'))
```

## Bootstrap:

1. Filter data down that we want to bootstrap (not really apart of the bootstrap process)

2. Non-parameteric Bootstrap:

We pull from our samples for non-parameteric bootstrap. Typically, we calculate some parameter. I calculate the mean for 50,000 participants :)

```{r}
m <- seq(1:100)
power <- data.frame('FACES' = numeric(100), 'AKS' = numeric(100), 'FES' = numeric(100),
                          'SCS' = numeric(100), 'FPPS' = numeric(100), 'SEAS' = numeric(100))

for (n in m) {
  B <- 5e4
  surveys <- as.character(unique(faces$Survey))
  pre.exp <- data.frame('FACES' = numeric(B), 'AKS' = numeric(B), 'FES' = numeric(B),
                          'SCS' = numeric(B), 'FPPS' = numeric(B), 'SEAS' = numeric(B))
  post.exp <- data.frame('FACES' = numeric(B), 'AKS' = numeric(B), 'FES' = numeric(B),
                          'SCS' = numeric(B), 'FPPS' = numeric(B), 'SEAS' = numeric(B))
  
  for (j in 1:6) {
    sample_faces_pre <- faces %>%
      filter(Time == 'Pre', 
             Group == 'Experimental',
             Survey == surveys[j]) %>%
      group_by(`Participant #`) %>%
      summarise(Total = sum(Response)) %>%
      ungroup()
    
    sample_faces_post <- faces %>%
      filter(Time == 'Post', 
             Group == 'Experimental',
             Survey == surveys[j]) %>%
      group_by(`Participant #`) %>%
      summarise(Total = sum(Response)) %>%
      ungroup()
  
  
    # Vector to store means
    m1 <- numeric()
    
    #pre sample mean and sd
    pre_mean <- mean(sample_faces_pre$Total)
    pre_sd <- sd(sample_faces_pre$Total)
    
    for (i in 1:B) {
      dist <- rnorm(n, mean=pre_mean, sd=pre_sd)
      m1[i] <- mean(dist)
    }
    pre.exp[surveys[j]] <- m1
    
    m2 <- numeric()
    
    #post sample mean and sd
    post_mean <- mean(sample_faces_post$Total)
    post_sd <- sd(sample_faces_post$Total)
    
    for (i in 1:B) {
      dist <- rnorm(n, mean=post_mean, sd=post_sd)
      m2[i] <- mean(dist)
    }
    post.exp[surveys[j]] <- m2
    
    post <- post.exp[,j] > pre.exp[,j]
    postSum <- sum(post)
    
    power[n, j] <- postSum / B
  
  }
}
```


```{r}


```

Comparing Pre and Post mean distributions:

```{r}
dist <- tibble(Time = c(rep('Pre', length(pre.exp$FACES)), rep('Post', length(post.exp$FACES))),
               Dist = c(pre.exp$FACES, post.exp$FACES)) %>%
  mutate(Time = factor(Time))
dist %>%
  ggplot() +
  geom_density(aes(x = Dist, fill = Time), alpha = 0.7)
```

