---
title: "Handling missing data"
output: html_notebook
---

Run this chunk first!
```{r setup}
library(tidyverse)
source('Data_Munging/FACES_fns.R')
```
 
Multiple ways to load data:

```{r}
# first way, specify data
fpath <- read_csv('../Data/FACES_data_Spring_2019_AllData.csv')
format_FACES(data = fpath)

# second way, specify path
format_FACES(path = '../Data/FACES_data_Spring_2019_AllData.csv')

# third way, just call the fucntion
(faces <- format_FACES())
```
 
## Summing Responses 
This section pivots teh data back to wide after summing up response by Participant for each Time (Pre and Post), Group (Int and Control), and Survey.  
 
```{r}
faces_sum <- faces %>%
  group_by(Survey, Time, Group) %>%
  summarise(score = sum(Response, na.rm = T))
  
faces_sum %>% 
  pivot_wider(id_cols = contains(c('Survey')), 
              names_from = contains(c('Group', 'Time')),
              values_from = score) %>%
  mutate(Post_Comparison = Experimental_Post - Control_Post,
         Cont_Comparison = Control_Post - Control_Pre,
         Exp_Comp        = Experimental_Post - Experimental_Pre)
  
```
 
## Missing data summary
The number of NA's or missing data is tallied in this section.

```{r}
faces_missing <- faces %>%
  filter(is.na(Response)) %>% 
  group_by(`Participant #`, Time, Group, Survey) %>%
  summarise(missing = n())
```
 
 
 
```{r}
table(faces_missing$`Participant #`, faces_missing$Survey)
```
 
 