---
title: "Bootstrap"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
faces <- read_csv('../Data/cleaned_FACES_data.csv', col_types = c('ffffdf'))
```

## Bootstrap:

1. Filter data down that we want to bootstrap (not really apart of the bootstrap process)

```{r}
sample_faces_pre <- faces %>%
  filter(Time == 'Pre', 
         Group == 'Experimental',
         Survey == 'FACES') %>%
  group_by(`Participant #`) %>%
  summarise(Total = sum(Response)) %>%
  ungroup()

sample_faces_post <- faces %>%
  filter(Time == 'Post', 
         Group == 'Experimental',
         Survey == 'FACES') %>%
  group_by(`Participant #`) %>%
  summarise(Total = sum(Response)) %>%
  ungroup()
```

2. Non-parameteric Bootstrap:

We pull from our samples for non-parameteric bootstrap. Typically, we calculate some parameter. I calculate the mean for 50,000 participants :)

```{r}
# Number of times to bootstrap
B <- 5e4

# Number of samples to pull
n <- 100

# Vector to store means
m1 <- numeric()

for (i in 1:B) {
  dist <- sample(sample_faces_pre$Total, size = n, replace = T)
  m1[i] <- mean(dist)
}
```

## Performing it again for the post score

```{r}
B <- 5e4
n <- 100
m2 <- numeric()

for (i in 1:B) {
  dist <- sample(sample_faces_post$Total, size = n, replace = T)
  m2[i] <- mean(dist)
}
```

Comparing Pre and Post mean distributions:

```{r}
dist <- tibble(Time = c(rep('Pre', length(m1)), rep('Post', length(m2))),
               Dist = c(m1, m2)) %>%
  mutate(Time = factor(Time))
dist %>%
  ggplot() +
  geom_density(aes(x = Dist, fill = Time), alpha = 0.7)
```

