---
title: "Bootstrap"
---

```{r}
library(tidyverse)
```


```{r}
faces <- read_csv('../Data/cleaned_FACES_data.csv', col_types = c('ffffdf'))
```

## Bootstrap:

1. Filter data down that we want to bootstrap (not really apart of the bootstrap process)

2. Non-parameteric Bootstrap:

We pull from our samples for non-parameteric bootstrap. Typically, we calculate some parameter. I calculate the mean for 50,000 participants :)

```{r}
#how many different n to test
m <- seq(from=5, to=60, by=5)
#power dataframe for non-parametric
power_norm <- data.frame('FACES' = numeric(length(m)), 'AKS' = numeric(length(m)), 
                         'FES' = numeric(length(m)), 'SCS' = numeric(length(m)), 
                         'FPPS' = numeric(length(m)), 'SEAS' = numeric(length(m)))


#power dataframe for parametric group
power_norm <- data.frame('FACES' = numeric(length(m)), 'AKS' = numeric(length(m)), 
                         'FES' = numeric(length(m)), 'SCS' = numeric(length(m)), 
                         'FPPS' = numeric(length(m)), 'SEAS' = numeric(length(m)))
```


```{r}
for (n in m) {
  # Number of times to bootstrap
  B <- 1e4
  #survey categories
  surveys <- as.character(unique(faces$Survey))
  #dataframe to hold simulation results
  pre.exp <- data.frame('FACES' = numeric(B), 'AKS' = numeric(B), 'FES' = numeric(B),
                          'SCS' = numeric(B), 'FPPS' = numeric(B), 'SEAS' = numeric(B))
  post.exp <- data.frame('FACES' = numeric(B), 'AKS' = numeric(B), 'FES' = numeric(B),
                          'SCS' = numeric(B), 'FPPS' = numeric(B), 'SEAS' = numeric(B))
  
  for (j in 1:6) {
    sample_faces_pre <- faces %>%
      filter(Time == 'Pre', 
             Group == 'Experimental',
             Survey == surveys[j]) %>%
      group_by(`Participant #`) %>%
      summarise(Total = sum(Response)) %>%
      ungroup()
    
    sample_faces_post <- faces %>%
      filter(Time == 'Post', 
             Group == 'Experimental',
             Survey == surveys[j]) %>%
      group_by(`Participant #`) %>%
      summarise(Total = sum(Response)) %>%
      ungroup()
  
    # Vector to store means
    m1 <- numeric()
    
    for (i in 1:B) {
      dist <- sample(sample_faces_pre$Total, size = n, replace = T)
      m1[i] <- mean(dist)
    }
    pre.exp[surveys[j]] <- m1
    
    #vector to store post means
    m2 <- numeric()
    
    for (i in 1:B) {
      dist <- sample(sample_faces_post$Total, size = n, replace = T)
      m2[i] <- mean(dist)
    }
    
    post.exp[surveys[j]] <- m2
    
    post <- post.exp[,j] > pre.exp[,j]
    postSum <- sum(post)
    
    power_data[n, j] <- postSum / B
  }
}
```

```{r}
  power <- cbind(power_data, power_norm)
  colNames <- c('FACESd', 'AKSd', 'FESd', 'SCSd', 'FPPSd', 'SEASd',
                'FACESn', 'AKSn', 'FESn', 'SCSn', 'FPPSn', 'SEASn')
  colnames(power) <- colNames
  power$indexes <- seq(1:60)
  
  ggplot(data=power, aes(x=indexes))+
      geom_line(aes(y=FACESd))+
      geom_line(aes(y=FACESn), linetype='twodash')
  lines(x=m, y=power[,7], col=1, lty=2)

```


Comparing Pre and Post mean distributions:

```{r}
dist <- tibble(Time = c(rep('Pre', length(m1)), rep('Post', length(m2))),
               Dist = c(m1, m2)) %>%
  mutate(Time = factor(Time))
dist %>%
  ggplot() +
  geom_density(aes(x = Dist, fill = Time), alpha = 0.7)
```

